_wandb:
    value:
        cli_version: 0.22.0
        e:
            4akgglu6cafsmffmt60na86iaaussq8f:
                args:
                    - config_test.yaml
                codePath: examples/training/cifar10/resnet.py
                codePathLocal: resnet.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "2014574526464"
                        used: "1615604572160"
                email: oliver@grainge.me
                executable: /home/oliver/miniconda3/bin/python
                git:
                    commit: 711ff9228abd9514c6021c8f253a7e2c74145fc7
                    remote: git@github.com:OliverGrainge/BitLab.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-b6b2499a-a3f4-818c-97fb-592660cd2938
                host: oliver-MS-7C91
                memory:
                    total: "67341307904"
                os: Linux-6.8.0-71-generic-x86_64-with-glibc2.39
                program: /home/oliver/github/BitLab/examples/training/cifar10/resnet.py
                python: CPython 3.11.4
                root: .
                startedAt: "2025-11-06T20:23:46.475024Z"
                writerId: 4akgglu6cafsmffmt60na86iaaussq8f
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 71
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 71
                - 103
            "3":
                - 7
                - 13
                - 16
                - 66
            "4": 3.11.4
            "5": 0.22.0
            "6": 4.51.3
            "8":
                - 2
            "12": 0.22.0
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
batch_size:
    value: 128
compute_per_class_metrics:
    value: false
data_root:
    value: ../../data
device:
    value: auto
focal_alpha:
    value: 0.25
focal_gamma:
    value: 2
label_smoothing:
    value: 0
layer_type:
    value: bitconv
learning_rate:
    value: 0.1
log_samples_every_n_epochs:
    value: 10
loss_type:
    value: cross_entropy
lr_scheduler:
    value: cosine
lr_warmup_steps:
    value: 0
max_lr_steps:
    value: 782
momentum:
    value: 0.9
num_classes:
    value: 10
num_epochs:
    value: 2
num_samples_to_log:
    value: 16
num_workers:
    value: 2
optimizer:
    value: sgd
quant_type:
    value: ai8pc_wpt
run_name:
    value: test
scheduler:
    value: cosine
seed:
    value: 42
sgd_momentum:
    value: 0.9
sgd_nesterov:
    value: true
top_k:
    value:
        - 1
        - 5
wandb_entity:
    value: null
wandb_project:
    value: bitlab-bitconv-cifar10-imageclass
weight_decay:
    value: 0.0005
