"""
Identify specific implementation differences between custom and HF models
"""

print("KEY DIFFERENCES TO CHECK:")
print("="*60)

print("\n1. ATTENTION MASK CREATION")
print("-" * 60)
print("Custom model (model.py line ~370):")
print("  causal_mask = torch.triu(..., diagonal=1)")
print("  Creates upper triangular mask with -inf above diagonal")
print("")
print("HF model (modeling_bitnet.py):")
print("  Uses create_causal_mask() from masking_utils")
print("  This may have different behavior!")
print("")

print("\n2. ROTARY EMBEDDINGS")
print("-" * 60)
print("Custom model:")
print("  - RotaryEmbedding.__init__ registers inv_freq as buffer")
print("  - forward() returns (cos, sin)")
print("  - No attention_scaling in basic implementation")
print("")
print("HF model (BitNetRotaryEmbedding):")
print("  - Has self.attention_scaling from rope_init_fn")
print("  - forward() returns: cos * self.attention_scaling, sin * self.attention_scaling")
print("  - Uses ROPE_INIT_FUNCTIONS which may include scaling!")
print("")

print("\n3. CACHE/POSITION HANDLING")
print("-" * 60)
print("Custom model:")
print("  - Simple position_ids generation")
print("  - No cache_position parameter")
print("  - No past_key_values caching in forward")
print("")
print("HF model:")
print("  - Uses cache_position throughout")
print("  - DynamicCache support")
print("  - More complex position/cache logic")
print("")

print("\n4. ATTENTION FORWARD SIGNATURE")
print("-" * 60)
print("Custom model Attention.forward():")
print("  (hidden_states, position_embeddings, attention_mask)")
print("")
print("HF model BitNetAttention.forward():")
print("  (hidden_states, position_embeddings, attention_mask,")
print("   past_key_values, cache_position, **kwargs)")
print("")

print("\n5. SUB-NORMALIZATION PLACEMENT")
print("-" * 60)
print("Custom model:")
print("  - attn_sub_norm AFTER attention output, BEFORE o_proj")
print("  Line ~245: attn_output = self.attn_sub_norm(attn_output)")
print("  Line ~246: attn_output = self.o_proj(attn_output)")
print("")
print("HF model:")
print("  - attn_sub_norm AFTER attention computation, BEFORE o_proj")
print("  Same placement - should match!")
print("")

print("\n6. ATTENTION IMPLEMENTATION")
print("-" * 60)
print("Custom model:")
print("  - Uses eager attention inline")
print("  - Direct computation in forward()")
print("")
print("HF model:")
print("  - Uses attention_interface = eager_attention_forward")
print("  - Can switch between implementations")
print("  - Has attention backend support")
print("")

print("\n7. CONFIG DIFFERENCES")
print("-" * 60)
print("Custom BitNetConfig:")
print("  - quant_type: 'ai8ptk_wpt'")
print("  - No rope_parameters dict")
print("  - Simple rope_theta float")
print("")
print("HF BitNetConfig:")
print("  - Has rope_parameters dict with 'rope_type' and 'rope_theta'")
print("  - More complex RoPE configuration")
print("")

print("\n" + "="*60)
print("MOST LIKELY CULPRITS:")
print("="*60)
print("\n1. ⚠️  ROTARY EMBEDDINGS SCALING")
print("   HF applies self.attention_scaling to cos/sin")
print("   Custom model doesn't have this!")
print("")
print("2. ⚠️  ATTENTION MASK FORMAT")
print("   create_causal_mask() may differ from torch.triu()")
print("")
print("3. ⚠️  POSITION_IDS/CACHE_POSITION")
print("   HF uses cache_position, custom uses position_ids")
print("   These may not be equivalent!")
print("")

print("\n" + "="*60)
print("RECOMMENDED FIXES:")
print("="*60)
print("\n1. Add attention_scaling to RotaryEmbedding:")
print("   In RotaryEmbedding.forward(), multiply cos and sin by attention_scaling")
print("")
print("2. Use HF's create_causal_mask:")
print("   Import from transformers and use their function")
print("")
print("3. Match exact HF config structure:")
print("   Use rope_parameters dict instead of simple rope_theta")